### ISSUE TITLE
Settings change in GCODE

### ISSUE THREAD

**Issue by sohail579** [just-trey/AnkerMake-M5-Profile#14]
Thanks for this project its been great but one thing i notice is that settings change from the Slice to the GCODE.  

So i create a Slice with a speed untouched at 250mm and when printing it says print speed exceeds the printer 300mm but this also changes its not always 300mm

also the print temp I have changed to 190 and it tells the printer to heat to 195

has anyone else experienced this?

**Comment by Vagabond80** [comment]
Regarding temperature. It is doing that for the inital layer by default, but you could change that. 
![image](https://user-images.githubusercontent.com/102099720/211807408-ce8e2cc0-2b6a-4d75-b9d4-ef78fe73a625.png)

And the speed issue has been mentioned under known issues, but it can be ignored afaik, since it won't print faster than 250mm/s anyway.

**Comment by DaveSpe** [comment]
+1 to this. 
This shouldn't be ignored, when I select 200 mm/s the slicer creates Gcode that sets the speed to 300 mm/s, yes it won't print faster than 250 but I want it printed at 200.

**Comment by just-trey** [comment]
@DaveSpe I have this as a known issue and also know the speed on the screen reports this, but I have been unable to find any line in any gcode that gets to that speed. Do you have an example you could share? If I get an example and the stl I can do additional analysis to try and correct this.

**Comment by sohail579** [comment]
> @DaveSpe I have this as a known issue and also know the speed on the screen reports this, but I have been unable to find any line in any gcode that gets to that speed. Do you have an example you could share? If I get an example and the stl I can do additional analysis to try and correct this.

do you mean the GCODE which has the speed as higher or a file which has for example 250 and it prints at 300 or should i say its reporting to print at 300?

**Comment by just-trey** [comment]
Yes does the gcode itself have values in it higher than 250 mms. They
calculation they use is very strange. I honestly don't trust what the
display says.

**Comment by just-trey** [comment]
After some suggestions and investigation, I found what is causing this to occur. It is the Flow equalization ratio added to Cura 5. I am not going to change the setting. If you want the printer to print at the input of the exact speed into Cura set this value to 0%. Otherwise, additional calculations are done within Cura that may create some speeds greater than set in the speed settings. Cura recommends using this feature to have better-quality prints so I am going to leave as is.
